spring:
  h2:
    console.enabled:true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:sample_db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect